#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: Input Method (fcitx5/ibus)
# ============================================================

step_input_method() {
    [[ "${INPUT_METHOD:-false}" == "false" || -z "${INPUT_METHOD}" ]] && return 0

    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Installing Input Method (${INPUT_METHOD_ENGINE})"
    echo ""

    local packages=()
    case "${INPUT_METHOD_ENGINE}" in
        fcitx5)
            packages=(
                "fcitx5|Fcitx5"
                "fcitx5-configtool|Fcitx5 Config Tool"
                "fcitx5-gtk|Fcitx5 GTK Module"
                "fcitx5-qt|Fcitx5 Qt Module"
                "fcitx5-chinese-addons|Fcitx5 Chinese Addons"
                "fcitx5-anthy|Fcitx5 Japanese (Anthy)"
                "fcitx5-hangul|Fcitx5 Korean (Hangul)"
                "fcitx5-mozc|Fcitx5 Japanese (Mozc)"
                "fcitx5-table-other|Fcitx5 Table Other"
            )
            ;;
        ibus)
            packages=(
                "ibus|IBus"
                "ibus-gtk|IBus GTK Module"
                "ibus-qt|IBus Qt Module"
                "ibus-libpinyin|IBus Chinese (Pinyin)"
                "ibus-anthy|IBus Japanese (Anthy)"
                "ibus-hangul|IBus Korean (Hangul)"
                "ibus-mozc|IBus Japanese (Mozc)"
                "ibus-table-other|IBus Table Other"
            )
            ;;
        *)
            log_warn "Unknown input method engine: ${INPUT_METHOD_ENGINE}"
            return 1
            ;;
    esac

    local failed=()
    for pkg_spec in "${packages[@]}"; do
        IFS='|' read -r pkg name <<< "${pkg_spec}"
        name="${name:-$pkg}"
        if ! execute install_pkg "${pkg}" "${name}"; then
            failed+=("${name}")
        fi
    done

    if [[ ${#failed[@]} -gt 0 ]]; then
        log_error "Failed to install input method packages: ${failed[*]}"
        return 1
    fi

    # Configure input method for Wayland
    configure_input_method_environment
    configure_input_method_autostart

    log_success "Input method (${INPUT_METHOD_ENGINE}) installed"
}

configure_input_method_environment() {
    log_info "Configuring input method environment variables..."

    local im_module=""
    local im_env=""

    case "${INPUT_METHOD_ENGINE}" in
        fcitx5)
            im_module="fcitx"
            im_env="@im=fcitx"
            ;;
        ibus)
            im_module="ibus"
            im_env="@im=ibus"
            ;;
    esac

    # Environment file for Wayland session
    execute mkdir -p "${HOME}/.config/environment.d"
    cat > "${HOME}/.config/environment.d/input-method.conf" << EOF
# Input Method Environment - Auto-generated by termux-wayland-installer
GTK_IM_MODULE=${im_module}
QT_IM_MODULE=${im_module}
XMODIFIERS=${im_env}
SDL_IM_MODULE=${im_module}
CLUTTER_IM_MODULE=${im_module}
EOF

    # Also add to shell profile for immediate effect
    if ! grep -q "GTK_IM_MODULE" "${HOME}/.bashrc" 2>/dev/null; then
        cat >> "${HOME}/.bashrc" << EOF

# Input Method (${INPUT_METHOD_ENGINE})
export GTK_IM_MODULE=${im_module}
export QT_IM_MODULE=${im_module}
export XMODIFIERS=${im_env}
export SDL_IM_MODULE=${im_module}
export CLUTTER_IM_MODULE=${im_module}
EOF
    fi

    # For zsh if present
    if [[ -f "${HOME}/.zshrc" ]] && ! grep -q "GTK_IM_MODULE" "${HOME}/.zshrc" 2>/dev/null; then
        cat >> "${HOME}/.zshrc" << EOF

# Input Method (${INPUT_METHOD_ENGINE})
export GTK_IM_MODULE=${im_module}
export QT_IM_MODULE=${im_module}
export XMODIFIERS=${im_env}
export SDL_IM_MODULE=${im_module}
export CLUTTER_IM_MODULE=${im_module}
EOF
    fi

    log_success "Input method environment configured"
}

configure_input_method_autostart() {
    log_info "Configuring input method autostart..."

    local desktop_file=""
    local exec_cmd=""

    case "${INPUT_METHOD_ENGINE}" in
        fcitx5)
            desktop_file="fcitx5.desktop"
            exec_cmd="fcitx5 -d"
            ;;
        ibus)
            desktop_file="ibus-daemon.desktop"
            exec_cmd="ibus-daemon -drx"
            ;;
    esac

    mkdir -p "${HOME}/.config/autostart"
    cat > "${HOME}/.config/autostart/${desktop_file}" << EOF
[Desktop Entry]
Type=Application
Name=${INPUT_METHOD_ENGINE^} Input Method
Exec=${exec_cmd}
X-GNOME-Autostart-enabled=true
OnlyShowIn=Hyprland;KDE;
EOF

    log_success "Input method autostart configured"
}

# Integration with Hyprland
configure_hyprland_input_method() {
    [[ "${INPUT_METHOD:-false}" != "true" ]] && return 0

    local im_module=""
    case "${INPUT_METHOD_ENGINE}" in
        fcitx5) im_module="fcitx" ;;
        ibus) im_module="ibus" ;;
    esac

    # Add input method environment to Hyprland config
    if [[ -f "${HOME}/.config/hypr/hyprland.conf" ]]; then
        # Check if already configured
        if ! grep -q "GTK_IM_MODULE" "${HOME}/.config/hypr/hyprland.conf" 2>/dev/null; then
            cat >> "${HOME}/.config/hypr/hyprland.conf" << EOF

# Input Method (${INPUT_METHOD_ENGINE})
env = GTK_IM_MODULE,${im_module}
env = QT_IM_MODULE,${im_module}
env = XMODIFIERS,@im=${INPUT_METHOD_ENGINE}
env = SDL_IM_MODULE,${im_module}
env = CLUTTER_IM_MODULE,${im_module}

# Autostart input method
exec-once = ${INPUT_METHOD_ENGINE} -d &
EOF
        fi
    fi
}

# Integration with KDE
configure_kde_input_method() {
    [[ "${INPUT_METHOD:-false}" != "true" ]] && return 0

    local im_module=""
    case "${INPUT_METHOD_ENGINE}" in
        fcitx5) im_module="fcitx" ;;
        ibus) im_module="ibus" ;;
    esac

    # KDE input method config (kcminputrc)
    mkdir -p "${HOME}/.config"
    cat > "${HOME}/.config/kcminputrc" << EOF
[General]
InputMethod=${INPUT_METHOD_ENGINE}

[GTK]
GTK_IM_MODULE=${im_module}
QT_IM_MODULE=${im_module}
XMODIFIERS=@im=${INPUT_METHOD_ENGINE}
EOF

    # Fcitx5 specific config for KDE
    if [[ "${INPUT_METHOD_ENGINE}" == "fcitx5" ]]; then
        mkdir -p "${HOME}/.config/fcitx5/profile"
        cat > "${HOME}/.config/fcitx5/profile/default" << 'EOF'
[Groups/0]
Name=Default
Default Layout=us
DefaultIM=keyboard-us

[Groups/0/Items/0]
Name=keyboard-us
Layout=us

[Groups/1]
Name=Chinese
Default Layout=us
DefaultIM=pinyin

[Groups/1/Items/0]
Name=keyboard-us
Layout=us

[Groups/1/Items/1]
Name=pinyin
Layout=us

[Groups/2]
Name=Japanese
Default Layout=us
DefaultIM=anthy

[Groups/2/Items/0]
Name=keyboard-us
Layout=us

[Groups/2/Items/1]
Name=anthy
Layout=us

[Groups/3]
Name=Korean
Default Layout=us
DefaultIM=hangul

[Groups/3/Items/0]
Name=keyboard-us
Layout=us

[Groups/3/Items/1]
Name=hangul
Layout=us

[Hotkeys]
TriggerKey=CTRL_SPACE
SwitchKey=ALT_SPACE
EOF
    fi
}

export -f step_input_method configure_input_method_environment configure_input_method_autostart
export -f configure_hyprland_input_method configure_kde_input_method