#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: Launchers & Desktop Configs
# ============================================================

step_launchers_configs() {
    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Configuring Launchers & Desktop Environment"
    echo ""

    local de="${DE}"
    [[ "${de}" == "kde" ]] && de="KDE" || de="Hyprland"

    if [[ "${DE}" == "hyprland" ]]; then
        configure_hyprland
    elif [[ "${DE}" == "kde" ]]; then
        configure_kde
    fi

    # Termux:API integration
    if cfg_is_true "features.termux_api"; then
        configure_termux_api
    fi

    log_success "Launchers & ${de} configs created"
}

configure_hyprland() {
    local theme="${THEME}"
    local variant="${THEME_VARIANT:-default}"

    # Hyprland config directory
    execute mkdir -p "${HOME}/.config/hypr"

    # Main hyprland.conf
    execute cat > "${HOME}/.config/hypr/hyprland.conf" << 'HYPREOF'
# ============================================================
# Hyprland Configuration - Auto-generated by termux-wayland-installer
# ============================================================

# Monitor
monitor = ,preferred,auto,auto

# Input (touchscreen support)
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(__COLOR_BORDER_ACTIVE__) rgba(__COLOR_BORDER_ACTIVE__)
    col.inactive_border = rgba(__COLOR_BORDER_INACTIVE__)
    layout = dwindle
    allow_tearing = false
    resize_on_border = true
}

# Decoration
decoration {
    rounding = 8
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
    }
    drop_shadow = true
    shadow_range = 12
    shadow_render_power = 3
    col.shadow = rgba(__COLOR_SHADOW__)
}

# Animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, myBezier, popin 80%
    animation = border, 1, 10, myBezier
    animation = borderangle, 1, 8, myBezier
    animation = fade, 1, 7, myBezier
    animation = workspaces, 1, 6, myBezier
}

# Window rules
windowrulev2 = float, class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = float, title:^(File Operation Progress|Copying|Moving)$
windowrulev2 = size 800 600, class:^(pavucontrol|blueman-manager)$
windowrulev2 = center, class:^(pavucontrol|blueman-manager|nm-connection-editor)$

# Startup
exec-once = waybar &
exec-once = swaync &
exec-once = wofi --show drun &

# Keybindings
$mainMod = SUPER

bind = $mainMod, Return, exec, foot
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen,
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit,
bind = $mainMod, Space, exec, wofi --show drun
bind = $mainMod, Left, movefocus, l
bind = $mainMod, Right, movefocus, r
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Down, movefocus, d
bind = $mainMod, Shift, Left, movewindow, l
bind = $mainMod, Shift, Right, movewindow, r
bind = $mainMod, Shift, Up, movewindow, u
bind = $mainMod, Shift, Down, movewindow, d
bind = $mainMod, CTRL, Left, resizeactive, -20 0
bind = $mainMod, CTRL, Right, resizeactive, 20 0
bind = $mainMod, CTRL, Up, resizeactive, 0 -20
bind = $mainMod, CTRL, Down, resizeactive, 0 20
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod, Shift, 1, movetoworkspace, 1
bind = $mainMod, Shift, 2, movetoworkspace, 2
bind = $mainMod, Shift, 3, movetoworkspace, 3
bind = $mainMod, Shift, 4, movetoworkspace, 4
bind = $mainMod, Shift, 5, movetoworkspace, 5
bind = $mainMod, Shift, 6, movetoworkspace, 6
bind = $mainMod, Shift, 7, movetoworkspace, 7
bind = $mainMod, Shift, 8, movetoworkspace, 8
bind = $mainMod, Shift, 9, movetoworkspace, 9
bind = $mainMod, Shift, 0, movetoworkspace, 10

# Touch gestures
gesture = 3, pinch, zoom
gesture = 3, swipe, workspace

HYPREOF

    # Apply theme colors
    apply_hyprland_theme

    # Waybar config
    configure_waybar

    # Wofi config
    configure_wofi

    # SwayNC config
    configure_swaync

    # Foot terminal config
    configure_foot

    # Input method integration
    configure_hyprland_input_method
}

apply_hyprland_theme() {
    local theme_colors
    theme_colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${theme_colors}"

    local border_active="${BASE16_BASE0E}"
    local border_inactive="${BASE16_BASE03}"
    local shadow="${BASE16_BASE01}"

    sed -i "s/__COLOR_BORDER_ACTIVE__/${border_active}/g" "${HOME}/.config/hypr/hyprland.conf"
    sed -i "s/__COLOR_BORDER_INACTIVE__/${border_inactive}/g" "${HOME}/.config/hypr/hyprland.conf"
    sed -i "s/__COLOR_SHADOW__/${shadow}/g" "${HOME}/.config/hypr/hyprland.conf"
}

configure_waybar() {
    execute mkdir -p "${HOME}/.config/waybar"

    execute cat > "${HOME}/.config/waybar/config.jsonc" << 'WAYBAREOF'
{
    "layer": "top",
    "position": "top",
    "height": 32,
    "modules-left": ["hyprland/workspaces", "hyprland/window"],
    "modules-center": ["clock"],
    "modules-right": ["pulseaudio", "network", "battery", "tray"],

    "hyprland/workspaces": {
        "format": "{icon}",
        "format-icons": {
            "1": "1", "2": "2", "3": "3", "4": "4",
            "5": "5", "6": "6", "7": "7", "8": "8",
            "9": "9", "10": "10"
        }
    },

    "hyprland/window": {
        "format": "{}",
        "max-length": 50
    },

    "clock": {
        "format": "{}",
        "format-alt": "",
        "tooltip-format": "<big>{:%A, %B %d}</big>\n{:%H:%M:%S}",
        "interval": 1
    },

    "pulseaudio": {
        "format": "{volume}% {icon}",
        "format-muted": "Muted",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        }
    },

    "network": {
        "format": "{ifname}: {ipaddr}",
        "format-disconnected": "Disconnected",
        "format-alt": "{essid}"
    },

    "battery": {
        "format": "{capacity}% {icon}",
        "format-charging": "{capacity}% ⚡",
        "format-plugged": "{capacity}% 🔌",
        "format-alt": "{time}",
        "threshold": 15
    },

    "tray": {
        "icon-size": 16,
        "spacing": 4
    }
}
WAYBAREOF

    execute cat > "${HOME}/.config/waybar/style.css" << 'WAYBARCSSEOF'
* {
    border: none;
    border-radius: 0;
    font-family: "JetBrains Mono Nerd Font", "Noto Sans", sans-serif;
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background: rgba(__COLOR_BG__, 0.9);
    color: __COLOR_FG__;
    border-bottom: 2px solid __COLOR_BORDER__;
}

#workspaces button {
    padding: 0 8px;
    background: transparent;
    color: __COLOR_MUTED__;
    transition: all 0.2s;
}

#workspaces button.focused {
    background: __COLOR_ACCENT__;
    color: __COLOR_BG__;
    border-radius: 4px;
}

#workspaces button:hover {
    background: __COLOR_HL__;
    color: __COLOR_FG__;
}

#window {
    padding: 0 12px;
    color: __COLOR_FG__;
}

#clock, #pulseaudio, #network, #battery, #tray {
    padding: 0 12px;
    color: __COLOR_FG__;
}

#tray > .needs-attention {
    background: __COLOR_WARN__;
}

#pulseaudio.muted {
    color: __COLOR_ERR__;
}

tooltip {
    background: __COLOR_BG__;
    border: 1px solid __COLOR_BORDER__;
    border-radius: 8px;
    padding: 8px;
}
WAYBARCSSEOF

    # Apply theme to waybar
    apply_waybar_theme
}

apply_waybar_theme() {
    local theme_colors
    theme_colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${theme_colors}"

    local bg="${BASE16_BASE00}"
    local fg="${BASE16_BASE05}"
    local muted="${BASE16_BASE03}"
    local accent="${BASE16_BASE0D}"
    local hl="${BASE16_BASE02}"
    local border="${BASE16_BASE03}"
    local warn="${BASE16_BASE0A}"
    local err="${BASE16_BASE08}"

    sed -i "s/__COLOR_BG__/${bg}/g; s/__COLOR_FG__/${fg}/g; s/__COLOR_MUTED__/${muted}/g" "${HOME}/.config/waybar/style.css"
    sed -i "s/__COLOR_ACCENT__/${accent}/g; s/__COLOR_HL__/${hl}/g; s/__COLOR_BORDER__/${border}/g" "${HOME}/.config/waybar/style.css"
    sed -i "s/__COLOR_WARN__/${warn}/g; s/__COLOR_ERR__/${err}/g" "${HOME}/.config/waybar/style.css"
}

configure_wofi() {
    execute mkdir -p "${HOME}/.config/wofi"

    execute cat > "${HOME}/.config/wofi/config" << 'WOFIEOF'
[general]
width=600
height=400
location=center
anchor=center
show=drun
prompt=Run:
filter=true
case-sensitive=false
normal-window=false
allow-images=true
insensitive=true
sort-order=default
gtk-dark=true
WOFIEOF

    execute cat > "${HOME}/.config/wofi/style.css" << 'WOFI_CSS_EOF'
* {
    font-family: "JetBrains Mono Nerd Font", "Noto Sans", sans-serif;
    font-size: 14px;
}

window {
    background-color: rgba(__COLOR_BG__, 0.95);
    border: 2px solid __COLOR_BORDER__;
    border-radius: 12px;
}

#input {
    margin: 12px;
    padding: 8px 12px;
    border: 1px solid __COLOR_BORDER__;
    border-radius: 8px;
    background-color: __COLOR_HL__;
    color: __COLOR_FG__;
}

#inner-box {
    margin: 0 12px 12px;
}

#outer-box {
    margin: 0;
}

#scroll {
    margin: 0;
}

#text {
    margin: 4px 8px;
    color: __COLOR_FG__;
}

#image {
    margin-right: 12px;
}

#entry {
    padding: 8px;
    border-radius: 8px;
}

#entry:selected {
    background-color: __COLOR_ACCENT__;
    color: __COLOR_BG__;
}

#entry:hover {
    background-color: __COLOR_HL__;
}
WOFI_CSS_EOF

    apply_wofi_theme
}

apply_wofi_theme() {
    local theme_colors
    theme_colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${theme_colors}"

    local bg="${BASE16_BASE00}"
    local fg="${BASE16_BASE05}"
    local hl="${BASE16_BASE02}"
    local border="${BASE16_BASE03}"
    local accent="${BASE16_BASE0D}"

    sed -i "s/__COLOR_BG__/${bg}/g; s/__COLOR_FG__/${fg}/g; s/__COLOR_HL__/${hl}/g" "${HOME}/.config/wofi/style.css"
    sed -i "s/__COLOR_BORDER__/${border}/g; s/__COLOR_ACCENT__/${accent}/g" "${HOME}/.config/wofi/style.css"
}

configure_swaync() {
    execute mkdir -p "${HOME}/.config/swaync"

    execute cat > "${HOME}/.config/swaync/config.json" << 'SWAYNCEOF'
{
    "position": "top-right",
    "layer": "overlay",
    "control-center-width": 400,
    "control-center-height": 500,
    "notification-window-width": 400,
    "notification-icon-size": 48,
    "notification-body-image-height": 100,
    "notification-body-image-width": 200,
    "timeout": 5,
    "timeout-low": 3,
    "timeout-critical": 0,
    "fit-to-screen": true,
    "control-center-layer": "top",
    "control-center-margin-top": 10,
    "control-center-margin-right": 10,
    "control-center-margin-bottom": 10,
    "control-center-margin-left": 10,
    "notification-2fa-action": false,
    "script-fail-notify": true,
    "widgets": [
        "title",
        "dnd",
        "notifications"
    ],
    "widget-config": {
        "title": {
            "text": "Notifications",
            "clear-all-button": true,
            "button-text": "Clear All"
        },
        "dnd": {
            "text": "Do Not Disturb",
            "on-icon": "",
            "off-icon": ""
        }
    }
}
SWAYNCEOF

    execute cat > "${HOME}/.config/swaync/style.css" << 'SWAYNC_CSS_EOF'
* {
    font-family: "JetBrains Mono Nerd Font", "Noto Sans", sans-serif;
}

#notification-window {
    background: rgba(__COLOR_BG__, 0.95);
    border: 1px solid __COLOR_BORDER__;
    border-radius: 12px;
}

#notification {
    background: __COLOR_HL__;
    border-radius: 8px;
    margin: 8px;
    padding: 8px;
}

#notification:hover {
    background: __COLOR_BG__;
    border: 1px solid __COLOR_ACCENT__;
}

#notification-title {
    color: __COLOR_FG__;
    font-weight: bold;
}

#notification-body {
    color: __COLOR_MUTED__;
}

#notification-time {
    color: __COLOR_MUTED__;
    font-size: 11px;
}

#control-center {
    background: rgba(__COLOR_BG__, 0.98);
    border: 1px solid __COLOR_BORDER__;
    border-radius: 12px;
}

#control-center-title {
    color: __COLOR_FG__;
    font-size: 16px;
    font-weight: bold;
    padding: 12px;
}

#control-center-clear-all {
    color: __COLOR_ACCENT__;
    font-weight: bold;
}

#dnd-toggle:checked {
    background: __COLOR_ACCENT__;
    color: __COLOR_BG__;
}
SWAYNC_CSS_EOF

    apply_swaync_theme
}

apply_swaync_theme() {
    local theme_colors
    theme_colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${theme_colors}"

    local bg="${BASE16_BASE00}"
    local fg="${BASE16_BASE05}"
    local muted="${BASE16_BASE03}"
    local hl="${BASE16_BASE02}"
    local border="${BASE16_BASE03}"
    local accent="${BASE16_BASE0D}"

    sed -i "s/__COLOR_BG__/${bg}/g; s/__COLOR_FG__/${fg}/g; s/__COLOR_MUTED__/${muted}/g" "${HOME}/.config/swaync/style.css"
    sed -i "s/__COLOR_HL__/${hl}/g; s/__COLOR_BORDER__/${border}/g; s/__COLOR_ACCENT__/${accent}/g" "${HOME}/.config/swaync/style.css"
}

configure_foot() {
    execute mkdir -p "${HOME}/.config/foot"

    execute cat > "${HOME}/.config/foot/foot.ini" << 'FOOTEOF'
[main]
font=JetBrainsMono Nerd Font:size=11
bold-font=JetBrainsMono Nerd Font:style=Bold:size=11
italic-font=JetBrainsMono Nerd Font:style=Italic:size=11
bold-italic-font=JetBrainsMono Nerd Font:style=Bold Italic:size=11

# Colors will be applied by theme
# background=__COLOR_BG__
# foreground=__COLOR_FG__

[scrollback]
lines=10000
multiplier=1.0

[mouse]
hide-when-typing=true

[keyboard]
ctrl+shift=c=copy
ctrl+shift+v=paste
FOOTEOF

    apply_foot_theme
}

apply_foot_theme() {
    local theme_colors
    theme_colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${theme_colors}"

    local bg="${BASE16_BASE00}"
    local fg="${BASE16_BASE05}"
    local black="${BASE16_BASE00}"
    local red="${BASE16_BASE08}"
    local green="${BASE16_BASE0B}"
    local yellow="${BASE16_BASE0A}"
    local blue="${BASE16_BASE0D}"
    local magenta="${BASE16_BASE0E}"
    local cyan="${BASE16_BASE0C}"
    local white="${BASE16_BASE05}"
    local bright_black="${BASE16_BASE03}"
    local bright_red="${BASE16_BASE08}"
    local bright_green="${BASE16_BASE0B}"
    local bright_yellow="${BASE16_BASE0A}"
    local bright_blue="${BASE16_BASE0D}"
    local bright_magenta="${BASE16_BASE0E}"
    local bright_cyan="${BASE16_BASE0C}"
    local bright_white="${BASE16_BASE07}"

    sed -i "s/^# background=.*/background=${bg}/" "${HOME}/.config/foot/foot.ini"
    sed -i "s/^# foreground=.*/foreground=${fg}/" "${HOME}/.config/foot/foot.ini"

    # Add color palette
    cat >> "${HOME}/.config/foot/foot.ini" << FOOTCOLORS

[colors]
# Standard colors
black=${black}
red=${red}
green=${green}
yellow=${yellow}
blue=${blue}
magenta=${magenta}
cyan=${cyan}
white=${white}

# Bright colors
bright-black=${bright_black}
bright-red=${bright_red}
bright-green=${bright_green}
bright-yellow=${bright_yellow}
bright-blue=${bright_blue}
bright-magenta=${bright_magenta}
bright-cyan=${bright_cyan}
bright-white=${bright_white}

# 256-color extensions (for apps that use them)
color16=${red}
color17=${green}
color18=${yellow}
color19=${blue}
color20=${magenta}
color21=${cyan}
color22=${bright_black}
color23=${bright_white}
FOOTCOLORS
}

configure_kde() {
    log_info "Creating comprehensive KDE Plasma 6 configuration..."
    echo ""

    local theme="${THEME}"
    local variant="${THEME_VARIANT:-default}"

    # Apply theme colors to KDE configs
    local theme_colors
    theme_colors=$(theme_get "${theme}" "${variant}")
    eval "${theme_colors}"

    local bg="${BASE16_BASE00}"
    local fg="${BASE16_BASE05}"
    local accent="${BASE16_BASE0D}"
    local hl="${BASE16_BASE02}"
    local border="${BASE16_BASE03}"
    local window_bg="${BASE16_BASE01}"
    local button_bg="${BASE16_BASE02}"
    local button_fg="${BASE16_BASE05}"
    local sel_bg="${BASE16_BASE0D}"
    local sel_fg="${BASE16_BASE00}"

    # ============================================================
    # 1. KWin Configuration (Window Manager)
    # ============================================================
    execute mkdir -p "${HOME}/.config"
    execute cat > "${HOME}/.config/kwinrc" << KWIN_EOF
[Compositing]
Backend=OpenGL
OpenGLIsUnsafe=false
ScaleMethod=auto
VSync=true
VSyncMethod=auto
MaxFPS=60
RefreshRate=60
AllowTearing=false
GLTextureFilter=1
GLPlatformInterface=wayland
GLStrictBinding=false
UnredirectFullscreen=true
UnredirectFullscreenTimeout=0

[Desktops]
# 4 virtual desktops by default
Number=4
Names=Desktop 1,Desktop 2,Desktop 3,Desktop 4
Rows=2

[Effect-DesktopGrid]
Border=15
BackgroundColor=0,0,0,180
GridColor=255,255,255,30
ZoomDuration=150

[Effect-PresentWindows]
Border=15
background=180
layout=0

[Effect-WindowThumbnail]
Size=150

[Effect-Slide]
Direction=Vertical
SlideDuration=150

[ElectricBorders]
Bottom=None
BottomLeft=DesktopGrid
BottomRight=PresentWindows
Left=None
Right=None
Time=500
Top=PresentWindows
TopLeft=Overview
TopRight=None

[Plugins]
kwin4_effect_blurEnabled=true
kwin4_effect_desktopgridEnabled=true
kwin4_effect_fadesEnabled=true
kwin4_effect_loginEnabled=true
kwin4_effect_logoutEnabled=true
kwin4_effect_magiclampEnabled=true
kwin4_effect_presentwindowsEnabled=true
kwin4_effect_slideEnabled=true
kwin4_effect_slidingpopupsEnabled=true
kwin4_effect_startupfeedbackEnabled=true
kwin4_effect_windowgeometryEnabled=true

[Scripts]
kwin4_script_scaleinEnabled=false

[TabBox]
LayoutName=grid
ShowDesktopTooltip=true

[Windows]
ActiveWindowMouseAction=Raise
ActiveWindowMouseActionOverride=Raise
AutoRaise=false
AutoRaiseInterval=0
BorderSnapZone=10
CenterSnapZone=0
ClickRaise=true
DelayFocusInterval=0
ElectricBorderMaximize=true
ElectricBorderTiling=true
FocusPolicy=ClickToFocus
FocusStealingPreventionLevel=1
MaximizeStep=25
MouseScrollFrameMaximized=false
MouseScrollFrameNotMaximized=false
NextFocusPrefersMouse=true
Placement=Smart
RaiseOnClick=true
RaiseOnDesktopChange=true
RollOverDesktops=true
SeparateScreenFocus=false
SnapZone=10
StrictWindowPlacement=false
TitlebarDoubleClick=Maximize
WindowGeometryTip=true
WindowTabScrolling=true
WindowTabScrollingSpeed=2

[SnapToScreenEdges]
Behavior=2

KWIN_EOF

    # ============================================================
    # 2. Plasma Panel Layout (Taskbar, System Tray, Clock)
    # ============================================================
    execute mkdir -p "${HOME}/.config"
    execute cat > "${HOME}/.config/plasma-org.kde.plasma.desktop-appletsrc" << PANEL_EOF
[ActionPlugins][0]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][1][Applets][2]
immutability=1
plugin=org.kde.plasma.private.systemtray

[Containments][1][Applets][2][Configuration]
ExtraItems=org.kde.plasma.networkmanagement,org.kde.plasma.volume,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.notifications,org.kde.plasma.keyboardindicator
HiddenItems=
KnownItems=org.kde.plasma.networkmanagement,org.kde.plasma.volume,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.notifications,org.kde.plasma.keyboardindicator,org.kde.plasma.bluetooth,org.kde.plasma.devicenotifier,org.kde.plasma.mediacontroller,org.kde.plasma.printmanager,org.kde.plasma.updates
ShownItems=org.kde.plasma.networkmanagement,org.kde.plasma.volume,org.kde.plasma.battery,org.kde.plasma.clipboard,org.kde.plasma.notifications,org.kde.plasma.keyboardindicator,org.kde.plasma.bluetooth
wheel:vertical:Role=SwitchDesktop

[Containments][1][Applets][3]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][1][Applets][3][Configuration]
ShowSeconds=true
ShowTimezone=false
Use24hFormat=true
DateFormat=short
ClockFont=Noto Sans,11,-1,5,50,0,0,0,0,0

[Containments][1][Applets][4]
immutability=1
plugin=org.kde.plasma.taskmanager

[Containments][1][Applets][4][Configuration]
ShowOnlyCurrentDesktop=false
ShowOnlyCurrentScreen=false
groupingStrategy=2
launchers=file:///usr/share/applications/org.kde.konsole.desktop,file:///usr/share/applications/org.kde.dolphin.desktop,file:///usr/share/applications/org.kde.kate.desktop,file:///usr/share/applications/org.kde.kcalc.desktop,file:///usr/share/applications/org.kde.spectacle.desktop
maxStripLength=200
sortOrder=1
onlyShowMinimized=false
onlyShowRunning=false
showOnlyCurrentActivity=false
showOnlyCurrentScreen=false
showTooltips=true
wheelEnabled=true
wheel:vertical:Role=SwitchTask

[Containments][1][Applets][5]
immutability=1
plugin=org.kde.plasma.startmenu

[Containments][1][Applets][5][Configuration]
displayMode=0
favoritesPortedToKAstats=true

[Containments][1][Applets][6]
immutability=1
plugin=org.kde.plasma.showdesktop

[Containments][1][Applets][7]
immutability=1
plugin=org.kde.plasma.pager

[Containments][1][Applets][7][Configuration]
displayedText=2
showWindowIcons=true
showWindowTitles=false

[Containments][1][General]
thickness=40
minimumSize=0

[ScreenConnectors]
Connected=true
Ids=0,0

PANEL_EOF

    # ============================================================
    # 3. Keyboard Shortcuts (Global, KWin, Plasma)
    # ============================================================
    execute cat > "${HOME}/.config/kglobalshortcutsrc" << SHORTCUTS_EOF
[component_data_org.kde.kglobalaccel][_k_friendly_name]=Global Shortcuts
[component_data_org.kde.kwin][_k_friendly_name]=KWin

[kwin]
_Toggle Desktop Grid=Meta+Tab,Meta+Tab,Toggle Desktop Grid
_Toggle Present Windows=Meta+A,Meta+A,Toggle Present Windows
_Toggle Overview=Meta+W,Meta+W,Toggle Overview
_Switch to Desktop 1=Meta+1,Meta+1,Switch to Desktop 1
_Switch to Desktop 2=Meta+2,Meta+2,Switch to Desktop 2
_Switch to Desktop 3=Meta+3,Meta+3,Switch to Desktop 3
_Switch to Desktop 4=Meta+4,Meta+4,Switch to Desktop 4
_Switch to Desktop 5=Meta+5,Meta+5,Switch to Desktop 5
_Switch to Desktop 6=Meta+6,Meta+6,Switch to Desktop 6
_Switch to Desktop 7=Meta+7,Meta+7,Switch to Desktop 7
_Switch to Desktop 8=Meta+8,Meta+8,Switch to Desktop 8
_Switch to Desktop 9=Meta+9,Meta+9,Switch to Desktop 9
_Switch to Desktop 10=Meta+0,Meta+0,Switch to Desktop 10
_Switch to Next Desktop=Meta+Right,Meta+Right,Switch to Next Desktop
_Switch to Previous Desktop=Meta+Left,Meta+Left,Switch to Previous Desktop
_Switch One Desktop to the Right=Meta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right
_Switch One Desktop to the Left=Meta+Ctrl+Left,Meta+Ctrl+Left,Switch One Desktop to the Left
_Switch One Screen to the Right=Meta+Shift+Right,Meta+Shift+Right,Switch One Screen to the Right
_Switch One Screen to the Left=Meta+Shift+Left,Meta+Shift+Left,Switch One Screen to the Left
_Toggle Window Maximized=Meta+M,Meta+M,Maximize Window
_Window to Next Screen=Meta+Shift+Up,Meta+Shift+Up,Window to Next Screen
_Window to Previous Screen=Meta+Shift+Down,Meta+Shift+Down,Window to Previous Screen
_Quick Tile Window to the Left=Meta+Left,Meta+Left,Quick Tile Window to the Left
_Quick Tile Window to the Right=Meta+Right,Meta+Right,Quick Tile Window to the Right
_Quick Tile Window to the Top=Meta+Up,Meta+Up,Quick Tile Window to the Top
_Quick Tile Window to the Bottom=Meta+Down,Meta+Down,Quick Tile Window to the Bottom
_Close Window=Meta+Q,Meta+Q,Close Window
_Kill Window=Meta+Shift+Q,Meta+Shift+Q,Kill Window
_Move Window Left=Meta+Shift+Left,Meta+Shift+Left,Move Window Left
_Move Window Right=Meta+Shift+Right,Meta+Shift+Right,Move Window Right
_Window Above Other Windows=Meta+Shift+F,Meta+Shift+F,Window Above Other Windows
_Window Below Other Windows=Meta+Shift+B,Meta+Shift+B,Window Below Other Windows
_Toggle Fullscreen=Meta+F11,Meta+F11,Toggle Fullscreen
_Switch Window=Meta+Tab,Meta+Tab,Switch Window
_Switch Window Reverse=Meta+Shift+Tab,Meta+Shift+Tab,Switch Window Reverse
_Walk Through Windows=Alt+Tab,Alt+Tab,Walk Through Windows
_Walk Through Windows Reverse=Alt+Shift+Tab,Alt+Shift+Tab,Walk Through Windows Reverse
_Walk Through Windows of Current Application=Alt+Alt_L,Alt+Alt_L,Walk Through Windows of Current Application
_Walk Through Windows of Current Application Reverse=Shift+Alt+Alt_L,Shift+Alt+Alt_L,Walk Through Windows of Current Application Reverse

[org.kde.krunner]
_Launch Application=Alt+F2,Alt+F2,Launch Application

[org.kde.plasma.desktop]
_Toggle Show Desktop=Meta+D,Meta+D,Show Desktop
_Show Application Dashboard=Meta+A,Meta+A,Show Application Dashboard
_Show Dashboard=Meta+S,Meta+S,Show Dashboard

[plasmashell]
_Toggle Overview=Meta+W,Meta+W,Toggle Overview
_Show Application Dashboard=Meta+A,Meta+A,Show Application Dashboard

[plasmashell][_k_friendly_name]=Plasma Shell

SHORTCUTS_EOF

    # ============================================================
    # 4. Plasma Theme & Colors (using selected theme)
    # ============================================================
    execute mkdir -p "${HOME}/.local/share/plasma/desktoptheme/custom-theme"
    execute cat > "${HOME}/.local/share/plasma/desktoptheme/custom-theme/metadata.desktop" << THEMEDESC_EOF
[Desktop Entry]
Name=Custom Theme (${theme} ${variant})
Comment=Auto-generated theme matching terminal/theme config
Author=termux-wayland-installer
Version=1.0
License=GPL
Type=Theme
X-Plasma-API=5.0
X-Plasma-DefaultWallpaper=false
X-Plasma-DefaultColorScheme=custom-theme
THEMEDESC_EOF

    execute mkdir -p "${HOME}/.local/share/plasma/look-and-feel/custom-theme/contents"
    execute cat > "${HOME}/.local/share/plasma/look-and-feel/custom-theme/metadata.desktop" << LNF_EOF
[Desktop Entry]
Name=Custom Theme (${theme} ${variant})
Comment=Auto-generated look and feel
Author=termux-wayland-installer
Version=1.0
License=GPL
Type=LookAndFeel
X-Plasma-API=5.0
X-Plasma-DefaultColorScheme=custom-theme
X-Plasma-DefaultWallpaper=false
LNF_EOF

    # Color scheme
    execute mkdir -p "${HOME}/.local/share/color-schemes"
    execute cat > "${HOME}/.local/share/color-schemes/custom-theme.colors" << COLORS_EOF
[ColorEffects:Disabled]
Color=#${bg:1}5
ColorAmount=0.55
ContrastColor=#${fg:1}
ContrastColorAmount=0.35
Intensity=0.05

[ColorEffects:Inactive]
Color=#${bg:1}5
ColorAmount=0.15
ContrastColor=#${fg:1}
ContrastColorAmount=0.05
Intensity=0.05

[Colors:Button]
BackgroundAlternate=#${window_bg:1}
BackgroundNormal=#${button_bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:Complementary]
BackgroundAlternate=#${window_bg:1}
BackgroundNormal=#${bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:Header]
BackgroundAlternate=#${hl:1}
BackgroundNormal=#${bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:Selection]
BackgroundAlternate=#${sel_bg:1}
BackgroundNormal=#${sel_bg:1}
ForegroundActive=#${sel_fg:1}
ForegroundInactive=#${sel_fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${sel_fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:Tooltip]
BackgroundAlternate=#${window_bg:1}
BackgroundNormal=#${bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:View]
BackgroundAlternate=#${bg:1}cc
BackgroundNormal=#${bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[Colors:Window]
BackgroundAlternate=#${window_bg:1}
BackgroundNormal=#${bg:1}
ForegroundActive=#${fg:1}
ForegroundInactive=#${fg:1}80
ForegroundLink=#${accent:1}
ForegroundNegative=#${BASE16_BASE08:1}
ForegroundNeutral=#${fg:1}
ForegroundNormal=#${fg:1}
ForegroundPositive=#${BASE16_BASE0B:1}
ForegroundVisited=#${BASE16_BASE0E:1}

[General]
Name=Custom Theme (${theme} ${variant})
shadeSortColumn=true
transparent=false

[KDE]
contrast=0.35
contrastFadeDuration=750

[WM]
activeBackground=#${bg:1}
activeForeground=#${fg:1}
activeBlend=#${accent:1}cc
activeBlendEnable=false
inactiveBackground=#${window_bg:1}
inactiveForeground=#${fg:1}80
inactiveBlend=#${hl:1}80
inactiveBlendEnable=false
COLORS_EOF

    # Apply color scheme
    execute cat > "${HOME}/.config/kdeglobals" << KDEGLOBALS_EOF
[General]
ColorScheme=custom-theme
widgetStyle=kvantum

[Icons]
Theme=Papirus-Dark

[KDE]
LookAndFeelPackage=org.kde.breeze.desktop
SingleClick=false

[KScreen]
ScaleFactor=1.0

[Locale]
Language=en_US
FormatsLocale=en_US

[TWM]
activeBorder=#${border:1}
inactiveBorder=#${border:1}50

KDEGLOBALS_EOF

    # ============================================================
    # 5. Window Decorations (Kvantum / Breeze)
    # ============================================================
    execute mkdir -p "${HOME}/.config/kvantum"
    execute cat > "${HOME}/.config/kvantum/kvantum.kvconfig" << KWINDECO_EOF
[General]
theme=CustomTheme
style=Kvantum
shadow=false
shadowSize=12
animationTime=150
cornerRadius=8
borderWidth=1
titlebarHeight=34
buttonSpacing=4
buttonSize=14
menuOpenness=0.95
toolbarItemSpacing=4
sideRadius=8
tabOverlap=3
sliderThickness=6
sliderDim=2
scrollBarWidth=8
scrollBarMargin=0
progressBarWidth=2
progressChunk=true
inactiveTitlebarBlend=0.5
inactiveBorderBlend=0.5
inactiveShadow=false
KWINDECO_EOF

    execute mkdir -p "${HOME}/.config/Kvantum/CustomTheme"
    execute cat > "${HOME}/.config/Kvantum/CustomTheme/CustomTheme.kvconfig" << KVTHEME_EOF
[General]
name=CustomTheme
author=termux-wayland-installer
version=1.0
description=Auto-generated theme matching ${theme} ${variant}

[Colors]
TitleBar.active=#${bg:1}
TitleBar.inactive=#${window_bg:1}
TitleBar.text.active=#${fg:1}
TitleBar.text.inactive=#${fg:1}80
Button.active=#${button_bg:1}
Button.inactive=#${button_bg:1}80
Button.text.active=#${fg:1}
Button.text.inactive=#${fg:1}80
Border.active=#${border:1}
Border.inactive=#${border:1}50
Window.active=#${bg:1}
Window.inactive=#${window_bg:1}
Shadow=#${border:1}40
Focus=#${accent:1}
Hover=#${hl:1}
Pressed=#${sel_bg:1}
Grip=#${border:1}

[Metrics]
titlebarHeight=34
borderWidth=1
cornerRadius=8
buttonSpacing=4
buttonSize=14
shadowSize=12
menuOpacity=0.95
tabOverlap=3
KVTHEME_EOF

    # ============================================================
    # 6. SDDM Autologin + Wayland Session
    # ============================================================
    execute mkdir -p "${HOME}/.config/sddm"
    execute cat > "${HOME}/.config/sddm/sddm.conf" << SDDM_EOF
[Autologin]
Relogin=false
Session=plasmawayland.desktop
User=${PROOT_USERNAME:-user}

[General]
InputMethod=

[Theme]
Current=breeze

[Users]
MaximumUid=65000
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true
SDDM_EOF

    # ============================================================
    # 7. Plasma Wallpaper (if URL provided)
    # ============================================================
    if [[ -n "${WALLPAPER_URL:-}" ]]; then
        execute cat > "${HOME}/.config/plasma-org.kde.plasma.desktop-appletsrc" << WALLPAPER_EOF
[Containments][1][Wallpaper][org.kde.image][General]
Image=${WALLPAPER_URL}
FillMode=2
WALLPAPER_EOF
    fi

    # ============================================================
    # 8. Konsole Profile (matching theme)
    # ============================================================
    execute mkdir -p "${HOME}/.local/share/konsole"
    execute cat > "${HOME}/.local/share/konsole/CustomTheme.profile" << KONSOLE_EOF
[Appearance]
ColorScheme=CustomTheme
Font=JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0
BlinkingCursorEnabled=true
CursorShape=1
TerminalColumns=120
TerminalRows=35

[General]
Name=CustomTheme
Parent=FALLBACK/
DefaultProfile=true

[Scrolling]
HistorySize=10000
ScrollBarPosition=2
AutomaticScroll=true

[Keyboard]
KeyBindings=Linux

[Mouse]
MousePointerShape=2
TripleClickSelectsLine=true
TripleClickMode=0

[TerminalFeatures]
BlinkCursor=true
CursorShape=1
BracketedPasteMode=true
FocusReporting=false
AutoDetectURL=true
KONSOLE_EOF

    execute cat > "${HOME}/.local/share/konsole/custom-theme.colorscheme" << KONSOLE_COLORS_EOF
[Background]
Color=#${bg:1}

[BackgroundFaint]
Color=#${window_bg:1}

[BackgroundIntense]
Color=#${hl:1}

[Color0]
Color=#${bg:1}

[Color0Faint]
Color=#${bg:1}80

[Color0Intense]
Color=#${hl:1}

[Color1]
Color=#${BASE16_BASE08:1}

[Color1Faint]
Color=#${BASE16_BASE08:1}80

[Color1Intense]
Color=#${BASE16_BASE08:1}

[Color2]
Color=#${BASE16_BASE0B:1}

[Color2Faint]
Color=#${BASE16_BASE0B:1}80

[Color2Intense]
Color=#${BASE16_BASE0B:1}

[Color3]
Color=#${BASE16_BASE0A:1}

[Color3Faint]
Color=#${BASE16_BASE0A:1}80

[Color3Intense]
Color=#${BASE16_BASE0A:1}

[Color4]
Color=#${BASE16_BASE0D:1}

[Color4Faint]
Color=#${BASE16_BASE0D:1}80

[Color4Intense]
Color=#${BASE16_BASE0D:1}

[Color5]
Color=#${BASE16_BASE0E:1}

[Color5Faint]
Color=#${BASE16_BASE0E:1}80

[Color5Intense]
Color=#${BASE16_BASE0E:1}

[Color6]
Color=#${BASE16_BASE0C:1}

[Color6Faint]
Color=#${BASE16_BASE0C:1}80

[Color6Intense]
Color=#${BASE16_BASE0C:1}

[Color7]
Color=#${fg:1}

[Color7Faint]
Color=#${fg:1}80

[Color7Intense]
Color=#${BASE16_BASE07:1}

[Foreground]
Color=#${fg:1}

[ForegroundFaint]
Color=#${fg:1}80

[ForegroundIntense]
Color=#${BASE16_BASE07:1}

[General]
Description=Custom theme matching ${theme} ${variant}
Opacity=1

[Selection]
Color=#${hl:1}

[TabBar]
ActiveBackground=#${sel_bg:1}
ActiveForeground=#${sel_fg:1}
InactiveBackground=#${window_bg:1}
InactiveForeground=#${fg:1}80
KONSOLE_COLORS_EOF

    # ============================================================
    # 9. Dolphin File Manager Settings
    # ============================================================
    execute cat > "${HOME}/.config/dolphinrc" << DOLPHIN_EOF
[General]
FirstRun=false
ViewMode=1
RememberOpenedTabs=true
ShowFullPath=true
ShowToolTips=true
EditableUrl=true
SplitView=false
ShowMenubar=false
NavigationBar=true
StatusBar=true
FilterBar=true
VersionControl=true
PreviewMode=0
ShowHiddenFiles=false
ShowDesktopFilesInHome=false
ShowDurationInTooltip=true
ShowFileSize=true
ShowFileSizeInTooltip=true

[MainWindow]
State=AAAA/wAAAAD9AAAAAwAAAAAAAABhAAABYwAAAA9zdWJ3aW5kb3cAAAAFAAAAVmlld3NvZgAAAAD/////AAAACkRvY2tXaWRnZXQAAAABAAAAMQAAAAMAAAAbYW5hbHlzaXMAAAAFAAAAVmlldwAAAAP/////AAAAClN0YXR1c0JhcgAAAAMA

[PreviewSettings]
MaximumRemoteSize=10485760
ShowPreview=true
SupportedMimetypes=image/*,video/*,audio/*,application/pdf,text/*,application/x-desktop

[VersionControl]
Enabled=true
DOLPHIN_EOF

    # ============================================================
    # 10. Kate Editor Settings
    # ============================================================
    execute cat > "${HOME}/.config/katerc" << KATE_EOF
[GUI]
ShowLineNumbers=true
ShowScrollbarMarks=true
ShowTabBar=true
TabBarPosition=1
TabWidthMode=1
TabIconPosition=0
ViInputMode=false

[KateView]
HighlightCurrentLine=true
ShowLineNumbers=true
ShowFoldingMarkers=true
StaticWordWrap=false
ShowTabBar=true
TabBarPosition=1
DynamicWordWrap=false
AutoIndent=true
SmartHome=true
HomeKeyInFirstColumn=true
ShowIconBorder=true
KeepTrailingSpaces=false
TrimTrailingSpacesOnSave=false
MixedIndent=false
TabWidth=4
ReplaceTabsOnSave=false
ReplaceTabs=false
IndentWidth=4
HighlightMatchingBrackets=true
HighlightCurrentLine=true

[Plugins]
kate_clipboard=true
kate_konsole=true
kate_openheader=true
kate_xmlcompletion=true
kate_ctags=true
katesnippets=true
kate_gitrepo=true
kate_closeexcept=true
kate_modelines=true
kate_textfilter=true
kate_project=true
kate_filetemplates=true
kate_quicksearch=true
kate_findinsession=true
kate_textstatistics=true
kate_spellcheck=true
kate_externaltools=true
kate_encodings=true
kate_backspaceindent=true
kate_clipboardhistory=true
kate_ktexteditor_variables=true
KATE_EOF

    # ============================================================
    # 11. Plasma Notification Settings
    # ============================================================
    execute cat > "${HOME}/.config/plasmanotifyrc" << NOTIFY_EOF
[Desktop Entry]
Name=Plasma Notifications

[Notifications]
AppletOrder=org.kde.plasma.notifications
EventMetaData=setup

[Notifications][EventMetaData][setup]
delay=0
expire-timeout=5000
isDesktopNotification=false
isPersistent=false
isSound=false
isUi=false
isWebNotification=false
maxCount=5
showInPopup=true
showMessage=true
soundFile=

[Notifications][EventMetaData][setup][Actions]
Action=default
Action=open
Action=close
NOTIFY_EOF

    # ============================================================
    # 12. Autostart (PipeWire, WirePlumber, Wallpaper)
    # ============================================================
    execute mkdir -p "${HOME}/.config/autostart"

    execute cat > "${HOME}/.config/autostart/pipewire.desktop" << EOF
[Desktop Entry]
Type=Application
Name=PipeWire
Exec=pipewire &
X-GNOME-Autostart-enabled=true
EOF

    execute cat > "${HOME}/.config/autostart/wireplumber.desktop" << EOF
[Desktop Entry]
Type=Application
Name=WirePlumber
Exec=wireplumber &
X-GNOME-Autostart-enabled=true
EOF

    if [[ -n "${WALLPAPER_URL:-}" ]]; then
        execute cat > "${HOME}/.config/autostart/wallpaper.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Set Wallpaper
Exec=plasma-apply-wallpaperimage "${WALLPAPER_URL}" &
X-GNOME-Autostart-enabled=true
EOF
    fi

    # ============================================================
    # 13. Touchpad/Tablet Support (if enabled)
    # ============================================================
    if [[ "${TABLET_SUPPORT:-false}" == "true" ]]; then
        execute cat > "${HOME}/.config/kcminputrc" << TABLET_EOF
[Tablet]
PressureSensitivity=1.0
PressureCurve=0
Mode=Absolute
CursorPosition=Screen
Rotate=0

[Touchpad]
NaturalScrolling=true
TapToClick=true
TapAndDrag=true
TwoFingerTap=RightClick
ThreeFingerTap=MiddleClick
ScrollTwoFingers=true
InvertScrollHoriz=false
InvertScrollVert=false
AccelProfile=adaptive
Speed=0.3
TABLET_EOF
    fi

    log_success "KDE Plasma 6 configuration complete!"
    log_info "Run '~/start-proot.sh' then 'startplasma-wayland' to test."

    # Input method integration
    configure_kde_input_method
}

configure_termux_api() {
    log_info "Configuring Termux:API integration"

    # Install termux-api if not present
    if ! command -v termux-toast &>/dev/null; then
        execute install_pkg "termux-api" "Termux:API"
    fi

    # Create helper scripts
    execute mkdir -p "${HOME}/.local/bin"

    execute cat > "${HOME}/.local/bin/termux-notify" << 'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Wrapper for termux-notification with proot support
if [ -n "$PROOT_DISTRO" ]; then
    # Running inside proot
    /data/data/com.termux/files/usr/bin/termux-notification "$@"
else
    # Running in Termux host
    /data/data/com.termux/files/usr/bin/termux-notification "$@"
fi
EOF
    execute chmod +x "${HOME}/.local/bin/termux-notify"

    execute cat > "${HOME}/.local/bin/termux-toast-wrapper" << 'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Wrapper for termux-toast with proot support
if [ -n "$PROOT_DISTRO" ]; then
    /data/data/com.termux/files/usr/bin/termux-toast "$@"
else
    /data/data/com.termux/files/usr/bin/termux-toast "$@"
fi
EOF
    execute chmod +x "${HOME}/.local/bin/termux-toast-wrapper"

    log_success "Termux:API integration configured"
}

export -f step_launchers_configs configure_hyprland configure_kde configure_termux_api apply_hyprland_theme configure_waybar apply_waybar_theme configure_wofi apply_wofi_theme configure_swaync apply_swaync_theme configure_foot apply_foot_theme