#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: Termux:Boot Autostart
# Auto-start Wayland session on Termux boot
# ============================================================

step_autostart() {
    [[ "${AUTOSTART:-false}" != "true" ]] && return 0

    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Configuring Termux:Boot Autostart"
    echo ""

    log_info "Creating autostart scripts for ${DE^}..."

    # Create termux:boot directory
    execute mkdir -p "${HOME}/.termux/boot"

    # Main boot script
    execute cat > "${HOME}/.termux/boot/wayland-autostart.sh" << 'BOOTEOF'
#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# Termux:Boot - Auto-start Wayland Session
# Auto-generated by termux-wayland-installer
# ============================================================

# Wait for Termux to be fully ready
sleep 3

# Setup environment
export TERMUX_PREFIX="/data/data/com.termux/files/usr"
export PATH="${TERMUX_PREFIX}/bin:${PATH}"
export HOME="/data/data/com.termux/files/home"
export TMPDIR="${TERMUX_PREFIX}/tmp"

# GPU Environment
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.6
export MESA_GLES_VERSION_OVERRIDE=3.2
export GALLIUM_DRIVER=zink
export MESA_LOADER_DRIVER_OVERRIDE=zink
export TU_DEBUG=noconform
export ZINK_DESCRIPTORS=lazy
export MESA_VK_WSI_PRESENT_MODE=immediate
export XDG_SESSION_TYPE=wayland
export XDG_RUNTIME_DIR="${TMPDIR}/wayland-0"
export XDG_DATA_DIRS="${TERMUX_PREFIX}/share:${XDG_DATA_DIRS:-}"
export XDG_CONFIG_DIRS="${TERMUX_PREFIX}/etc/xdg:${XDG_CONFIG_DIRS:-}"

# GPU Driver detection
GPU_VENDOR=$(getprop ro.hardware.egl 2>/dev/null || echo "")
if [[ "${GPU_VENDOR}" == *"adreno"* ]] || \
   [[ "$(getprop ro.product.brand 2>/dev/null)" =~ [Ss]amsung|[Oo]ne[Pp]lus|[Xx]iaomi|[Rr]edmi|[Pp]oco|[Mm]oto|motorola ]]; then
    export VK_ICD_FILENAMES="${TERMUX_PREFIX}/share/vulkan/icd.d/freedreno_icd.aarch64.json"
    export GPU_DRIVER="freedreno"
else
    export GPU_DRIVER="zink"
fi

# Create runtime directory
mkdir -p "${XDG_RUNTIME_DIR}"

# Start PipeWire (if not already running)
if ! pgrep -x "pipewire" >/dev/null 2>&1; then
    "${TERMUX_PREFIX}/bin/pipewire" &
    sleep 1
fi
if ! pgrep -x "wireplumber" >/dev/null 2>&1; then
    "${TERMUX_PREFIX}/bin/wireplumber" &
    sleep 1
fi
if ! pgrep -x "pipewire-pulse" >/dev/null 2>&1; then
    "${TERMUX_PREFIX}/bin/pipewire-pulse" &
    sleep 1
fi

# Start termux-x11 (Wayland compositor host)
if ! pgrep -x "termux-x11" >/dev/null 2>&1; then
    "${TERMUX_PREFIX}/bin/termux-x11" :0 -ac &
    sleep 2
fi

# Start Wayland compositor based on DE
case "__DE__" in
    hyprland)
        export XDG_CURRENT_DESKTOP=Hyprland
        export WAYLAND_DISPLAY=wayland-0
        export QT_QPA_PLATFORM=wayland
        export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
        export SDL_VIDEODRIVER=wayland
        export CLUTTER_BACKEND=wayland

        # Source input method env if exists
        [[ -f "${HOME}/.config/environment.d/input-method.conf" ]] && source "${HOME}/.config/environment.d/input-method.conf"

        # Start Hyprland
        exec "${TERMUX_PREFIX}/bin/Hyprland" > "${TMPDIR}/hyprland.log" 2>&1
        ;;
    kde)
        export XDG_CURRENT_DESKTOP=KDE
        export WAYLAND_DISPLAY=wayland-0
        export QT_QPA_PLATFORM=wayland
        export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
        export KDE_FULL_SESSION=true
        export KDE_SESSION_VERSION=6
        export XDG_SESSION_DESKTOP=KDE
        export XDG_SESSION_TYPE=wayland

        # Source input method env if exists
        [[ -f "${HOME}/.config/environment.d/input-method.conf" ]] && source "${HOME}/.config/environment.d/input-method.conf"

        # Start Plasma Wayland
        exec "${TERMUX_PREFIX}/bin/startplasma-wayland" > "${TMPDIR}/plasma.log" 2>&1
        ;;
    *)
        echo "Unknown DE: __DE__" > "${TMPDIR}/autostart-error.log"
        exit 1
        ;;
esac
BOOTEOF

    # Replace placeholder
    sed -i "s/__DE__/${DE}/g" "${HOME}/.termux/boot/wayland-autostart.sh"

    execute chmod +x "${HOME}/.termux/boot/wayland-autostart.sh"

    # Also create a simple starter script for manual use
    execute cat > "${HOME}/.termux/boot/wayland-start.sh" << 'STARTEOF'
#!/data/data/com.termux/files/usr/bin/bash
# Manual Wayland starter (can be run from Termux widget)
# Auto-generated by termux-wayland-installer

DE="__DE__"
HOME="/data/data/com.termux/files/home"
TERMUX_PREFIX="/data/data/com.termux/files/usr"
TMPDIR="${TERMUX_PREFIX}/tmp"

export PATH="${TERMUX_PREFIX}/bin:${PATH}"
export HOME="${HOME}"
export TMPDIR="${TMPDIR}"

# GPU Environment
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.6
export MESA_GLES_VERSION_OVERRIDE=3.2
export GALLIUM_DRIVER=zink
export MESA_LOADER_DRIVER_OVERRIDE=zink
export TU_DEBUG=noconform
export ZINK_DESCRIPTORS=lazy
export MESA_VK_WSI_PRESENT_MODE=immediate
export XDG_SESSION_TYPE=wayland
export XDG_RUNTIME_DIR="${TMPDIR}/wayland-0"
export XDG_DATA_DIRS="${TERMUX_PREFIX}/share:${XDG_DATA_DIRS:-}"
export XDG_CONFIG_DIRS="${TERMUX_PREFIX}/etc/xdg:${XDG_CONFIG_DIRS:-}"

GPU_VENDOR=$(getprop ro.hardware.egl 2>/dev/null || echo "")
if [[ "${GPU_VENDOR}" == *"adreno"* ]] || \
   [[ "$(getprop ro.product.brand 2>/dev/null)" =~ [Ss]amsung|[Oo]ne[Pp]lus|[Xx]iaomi|[Rr]edmi|[Pp]oco|[Mm]oto|motorola ]]; then
    export VK_ICD_FILENAMES="${TERMUX_PREFIX}/share/vulkan/icd.d/freedreno_icd.aarch64.json"
fi

mkdir -p "${XDG_RUNTIME_DIR}"

# Start PipeWire if needed
for svc in pipewire wireplumber pipewire-pulse; do
    if ! pgrep -x "${svc}" >/dev/null 2>&1; then
        "${TERMUX_PREFIX}/bin/${svc}" &
        sleep 0.5
    fi
done

# Start termux-x11 if needed
if ! pgrep -x "termux-x11" >/dev/null 2>&1; then
    "${TERMUX_PREFIX}/bin/termux-x11" :0 -ac &
    sleep 2
fi

# Source input method
[[ -f "${HOME}/.config/environment.d/input-method.conf" ]] && source "${HOME}/.config/environment.d/input-method.conf"

case "${DE}" in
    hyprland)
        export XDG_CURRENT_DESKTOP=Hyprland
        export WAYLAND_DISPLAY=wayland-0
        export QT_QPA_PLATFORM=wayland
        export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
        export SDL_VIDEODRIVER=wayland
        export CLUTTER_BACKEND=wayland
        exec "${TERMUX_PREFIX}/bin/Hyprland"
        ;;
    kde)
        export XDG_CURRENT_DESKTOP=KDE
        export WAYLAND_DISPLAY=wayland-0
        export QT_QPA_PLATFORM=wayland
        export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
        export KDE_FULL_SESSION=true
        export KDE_SESSION_VERSION=6
        export XDG_SESSION_DESKTOP=KDE
        exec "${TERMUX_PREFIX}/bin/startplasma-wayland"
        ;;
esac
STARTEOF

    sed -i "s/__DE__/${DE}/g" "${HOME}/.termux/boot/wayland-start.sh"
    execute chmod +x "${HOME}/.termux/boot/wayland-start.sh"

    # Create Termux Widget shortcut
    execute mkdir -p "${HOME}/.shortcuts"
    execute cat > "${HOME}/.shortcuts/Start Wayland.sh" << 'SHORTCUTEOF'
#!/data/data/com.termux/files/usr/bin/bash
# Termux Widget: Start Wayland Session
bash ~/.termux/boot/wayland-start.sh
SHORTCUTEOF
    execute chmod +x "${HOME}/.shortcuts/Start Wayland.sh"

    log_success "Termux:Boot autostart configured for ${DE^}"
    log_info "  ~/.termux/boot/wayland-autostart.sh (auto on boot)"
    log_info "  ~/.termux/boot/wayland-start.sh (manual)"
    log_info "  ~/.shortcuts/Start Wayland.sh (widget)"
}

# Disable autostart (for uninstall/update)
disable_autostart() {
    log_info "Disabling Termux:Boot autostart..."
    rm -f "${HOME}/.termux/boot/wayland-autostart.sh"
    rm -f "${HOME}/.termux/boot/wayland-start.sh"
    rm -f "${HOME}/.shortcuts/Start Wayland.sh"
    log_success "Autostart disabled"
}

export -f step_autostart disable_autostart