#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: Wallpaper Download & Apply
# Downloads wallpaper from URL, verifies SHA256, applies to DE
# ============================================================

step_wallpaper() {
    [[ -z "${WALLPAPER_URL:-}" ]] && return 0

    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Downloading & Applying Wallpaper"
    echo ""

    local wallpaper_dir="${HOME}/.local/share/backgrounds"
    local wallpaper_file="${wallpaper_dir}/wallpaper.jpg"
    local temp_file="${wallpaper_file}.tmp"

    execute mkdir -p "${wallpaper_dir}"

    log_info "Downloading wallpaper from: ${WALLPAPER_URL}"

    # Download with retries
    local max_tries=3
    local success=false

    for attempt in $(seq 1 "${max_tries}"); do
        if execute wget -L -q --timeout=30 -O "${temp_file}" "${WALLPAPER_URL}" 2>/dev/null; then
            success=true
            break
        fi
        log_warn "Download attempt ${attempt}/${max_tries} failed, retrying..."
        sleep 2
    done

    if [[ "${success}" != "true" ]]; then
        log_error "Failed to download wallpaper after ${max_tries} attempts"
        return 1
    fi

    # Verify SHA256 if provided
    if [[ -n "${WALLPAPER_SHA256:-}" ]]; then
        log_info "Verifying SHA256 checksum..."
        local actual_sha256
        actual_sha256=$(sha256sum "${temp_file}" 2>/dev/null | awk '{print $1}')

        if [[ "${actual_sha256}" != "${WALLPAPER_SHA256}" ]]; then
            log_error "SHA256 mismatch!"
            log_error "  Expected: ${WALLPAPER_SHA256}"
            log_error "  Actual:   ${actual_sha256}"
            execute rm -f "${temp_file}"
            return 1
        fi
        log_success "SHA256 verified"
    fi

    # Move to final location
    execute mv "${temp_file}" "${wallpaper_file}"
    log_success "Wallpaper saved to ${wallpaper_file}"

    # Apply wallpaper based on DE
    apply_wallpaper_to_de "${wallpaper_file}"

    log_success "Wallpaper applied to ${DE^}"
}

apply_wallpaper_to_de() {
    local wallpaper_file="$1"

    case "${DE}" in
        hyprland)
            # Hyprland uses hyprpaper
            execute mkdir -p "${HOME}/.config/hypr"
            execute cat > "${HOME}/.config/hypr/hyprpaper.conf" << HYPRPAPER_EOF
# Hyprpaper config - Auto-generated by termux-wayland-installer
preload = ${wallpaper_file}
wallpaper = ,${wallpaper_file}
HYPRPAPER_EOF
            log_info "Hyprpaper config created"
            ;;

        kde)
            # KDE uses plasma-apply-wallpaperimage (runtime) or config
            execute mkdir -p "${HOME}/.config"
            execute cat > "${HOME}/.config/plasma-org.kde.plasma.desktop-appletsrc" << PLASMA_WP_EOF
[Containments][1][Wallpaper][org.kde.image][General]
Image=file://${wallpaper_file}
FillMode=2
PLASMA_WP_EOF

            # Also create autostart to apply at runtime
            execute mkdir -p "${HOME}/.config/autostart"
            execute cat > "${HOME}/.config/autostart/wallpaper.desktop" << WP_AUTOSTART_EOF
[Desktop Entry]
Type=Application
Name=Set Wallpaper
Exec=plasma-apply-wallpaperimage "file://${wallpaper_file}" &
X-GNOME-Autostart-enabled=true
OnlyShowIn=KDE;
WP_AUTOSTART_EOF
            log_info "KDE wallpaper config created"
            ;;

        *)
            log_warn "Unknown DE for wallpaper: ${DE}"
            ;;
    esac
}

# Generate gradient fallback if no wallpaper URL
generate_gradient_wallpaper() {
    local output_file="$1"
    local colors
    colors=$(theme_get "${THEME}" "${THEME_VARIANT:-default}")
    eval "${colors}"

    # Create a simple gradient using ImageMagick if available, else skip
    if command -v convert &>/dev/null; then
        log_info "Generating gradient wallpaper..."
        execute convert -size 1920x1080 gradient:"${BASE16_BASE00}"-"${BASE16_BASE01}" "${output_file}" 2>/dev/null || true
    fi
}

export -f step_wallpaper apply_wallpaper_to_de generate_gradient_wallpaper