#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: SSH Server in Proot
# Configures SSH server inside proot container
# ============================================================

step_ssh_setup() {
    [[ "${SETUP_SSH:-false}" != "true" ]] && return 0
    [[ "${INSTALL_PROOT:-true}" != "true" ]] && return 0

    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Configuring SSH Server in Proot (${PROOT_LABEL})"
    echo ""

    log_info "Setting up SSH server in proot container..."

    # Generate SSH host keys and configure sshd
    execute proot-distro login "${PROOT_DISTRO}" -- bash -c "
        set -euo pipefail

        # Install openssh if not present
        case '${PROOT_DISTRO}' in
            archlinux|arch) pacman -S --noconfirm --needed openssh ;;
            debian|ubuntu) apt-get update && apt-get install -y openssh-server ;;
            fedora) dnf install -y openssh-server ;;
            alpine) apk add openssh-server ;;
        esac

        # Generate host keys
        ssh-keygen -A

        # Configure sshd_config for proot environment
        cat > /etc/ssh/sshd_config << 'SSHD_EOF'
# SSH Server Config - Auto-generated by termux-wayland-installer
Port 2222
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Security
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Network
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost yes
AllowTcpForwarding yes
GatewayPorts no

# Environment
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/ssh/sftp-server

# Logging
SyslogFacility AUTH
LogLevel INFO

# Performance
UseDNS no
GSSAPIAuthentication no
SSHD_EOF

        # Create authorized_keys for proot user
        mkdir -p /home/${PROOT_USERNAME}/.ssh
        chmod 700 /home/${PROOT_USERNAME}/.ssh

        # Add host SSH keys if they exist
        if [[ -f /data/data/com.termux/files/home/.ssh/id_ed25519.pub ]]; then
            cat /data/data/com.termux/files/home/.ssh/id_ed25519.pub >> /home/${PROOT_USERNAME}/.ssh/authorized_keys
        fi
        if [[ -f /data/data/com.termux/files/home/.ssh/id_rsa.pub ]]; then
            cat /data/data/com.termux/files/home/.ssh/id_rsa.pub >> /home/${PROOT_USERNAME}/.ssh/authorized_keys
        fi

        chmod 600 /home/${PROOT_USERNAME}/.ssh/authorized_keys
        chown -R ${PROOT_USERNAME}:${PROOT_USERNAME} /home/${PROOT_USERNAME}/.ssh

        # Create SSH start script
        cat > /home/${PROOT_USERNAME}/.ssh/start-ssh.sh << 'START_EOF'
#!/bin/bash
# Start SSH server in proot
/usr/bin/ssh-keygen -A 2>/dev/null
exec /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config
START_EOF
        chmod +x /home/${PROOT_USERNAME}/.ssh/start-ssh.sh

        echo 'SSH server configured on port 2222'
    " 2>/dev/null || log_warn "Some SSH setup steps had issues"

    # Create host-side SSH wrapper
    execute cat > "${HOME}/.local/bin/proot-ssh" << 'SSH_WRAPPER_EOF'
#!/data/data/com.termux/files/usr/bin/bash
# SSH into proot container
# Auto-generated by termux-wayland-installer

PROOT_DISTRO="__PROOT_DISTRO__"
PROOT_USER="__PROOT_USERNAME__"
PORT=2222

usage() {
    echo "Usage: proot-ssh [user@]host [command]"
    echo "       proot-ssh -p port [user@]host [command]"
    echo ""
    echo "Connects to proot container SSH server (port 2222)"
    echo "Run inside proot: ~/.ssh/start-ssh.sh"
}

# Check if proot SSH is running
if ! proot-distro login "${PROOT_DISTRO}" -- bash -c "pgrep -x sshd >/dev/null 2>&1"; then
    echo "[!] SSH server not running in proot."
    echo "    Start it inside proot with: ~/.ssh/start-ssh.sh"
    echo "    Or add to proot autostart."
    exit 1
fi

# Forward to ssh
exec ssh -p "${PORT}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${PROOT_USER}@localhost" "$@"
SSH_WRAPPER_EOF

    sed -i "s/__PROOT_DISTRO__/${PROOT_DISTRO}/g" "${HOME}/.local/bin/proot-ssh"
    sed -i "s/__PROOT_USERNAME__/${PROOT_USERNAME}/g" "${HOME}/.local/bin/proot-ssh"
    execute chmod +x "${HOME}/.local/bin/proot-ssh"

    # Add SSH autostart to proot bashrc (optional)
    execute proot-distro login "${PROOT_DISTRO}" -- bash -c "
        if ! grep -q 'start-ssh.sh' /home/${PROOT_USERNAME}/.bashrc 2>/dev/null; then
            echo '' >> /home/${PROOT_USERNAME}/.bashrc
            echo '# Auto-start SSH server' >> /home/${PROOT_USERNAME}/.bashrc
            echo 'if ! pgrep -x sshd >/dev/null 2>&1; then' >> /home/${PROOT_USERNAME}/.bashrc
            echo '    ~/.ssh/start-ssh.sh > ~/.ssh/ssh.log 2>&1 &' >> /home/${PROOT_USERNAME}/.bashrc
            echo 'fi' >> /home/${PROOT_USERNAME}/.bashrc
        fi
    " 2>/dev/null || true

    log_success "SSH server configured in proot (${PROOT_LABEL})"
    log_info "  Port: 2222"
    log_info "  User: ${PROOT_USERNAME}"
    log_info "  Connect: proot-ssh"
    log_info "  Start in proot: ~/.ssh/start-ssh.sh"
}

export -f step_ssh_setup