#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# termux-wayland-installer - Step: Tablet/Stylus Support
# Configures Wacom, S-Pen, and other tablet devices for Wayland
# ============================================================

step_tablet_support() {
    [[ "${TABLET_SUPPORT:-false}" != "true" ]] && return 0

    print_step $((++CURRENT_STEP)) "${TOTAL_STEPS}" "Configuring Tablet/Stylus Support"
    echo ""

    log_info "Installing tablet packages and configuring input..."

    # Install tablet packages
    local packages=(
        "libwacom|Libwacom (tablet database)"
        "libinput|Libinput (input handling)"
        "kde-cli-tools|KDE CLI Tools (for kcminputrc)"  # For KDE
    )

    local failed=()
    for pkg_spec in "${packages[@]}"; do
        IFS='|' read -r pkg name <<< "${pkg_spec}"
        name="${name:-$pkg}"
        if ! execute install_pkg "${pkg}" "${name}"; then
            failed+=("${name}")
        fi
    done

    if [[ ${#failed[@]} -gt 0 ]]; then
        log_warn "Some tablet packages failed: ${failed[*]}"
    fi

    # Configure udev rules for tablet devices
    configure_tablet_udev_rules

    # Configure libinput for tablets
    configure_libinput_tablet

    # DE-specific configuration
    case "${DE}" in
        hyprland)
            configure_hyprland_tablet
            ;;
        kde)
            configure_kde_tablet
            ;;
    esac

    # Input method tablet config (fcitx5)
    if [[ "${INPUT_METHOD:-false}" == "true" && "${INPUT_METHOD_ENGINE:-fcitx5}" == "fcitx5" ]]; then
        configure_fcitx5_tablet
    fi

    log_success "Tablet/Stylus support configured for ${DE^}"
}

configure_tablet_udev_rules() {
    log_info "Creating udev rules for tablet devices..."

    execute mkdir -p "${HOME}/.config/udev/rules.d"

    # Udev rules for Wacom, S-Pen, and generic tablets
    execute cat > "${HOME}/.config/udev/rules.d/99-tablet.rules" << 'UDEV_EOF'
# Tablet/Stylus udev rules - Auto-generated by termux-wayland-installer
# Wacom devices
ATTRS{name}=="Wacom*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="Wacom*", ENV{ID_INPUT_TABLET}=="1", TAG+="uaccess"

# Samsung S-Pen
ATTRS{name}=="*S-Pen*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="*S-Pen*", ENV{ID_INPUT_TABLET}=="1", TAG+="uaccess"
ATTRS{name}=="sec_touchscreen", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"

# Generic HID tablets
SUBSYSTEM=="hidraw", ATTRS{name}=="*Tablet*", TAG+="uaccess"
SUBSYSTEM=="hidraw", ATTRS{name}=="*tablet*", TAG+="uaccess"
SUBSYSTEM=="hidraw", ATTRS{name}=="*Pen*", TAG+="uaccess"

# Huion, XP-Pen, Gaomon, etc.
ATTRS{name}=="HUION*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="XP-PEN*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="GAOMON*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="VEIKK*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"
ATTRS{name}=="UGEE*", ENV{LIBINPUT_TABLET_TOOL}=="1", TAG+="uaccess"

# Set permissions for uinput (for virtual tablet tools)
KERNEL=="uinput", MODE="0660", GROUP="input", TAG+="uaccess"
UDEV_EOF

    log_info "Udev rules created at ~/.config/udev/rules.d/99-tablet.rules"
    log_warn "Note: udev rules require Termux:API or root to take effect immediately"
}

configure_libinput_tablet() {
    log_info "Configuring libinput for tablet support..."

    execute mkdir -p "${HOME}/.config/libinput"

    execute cat > "${HOME}/.config/libinput/libinput.conf" << 'LIBINPUT_EOF'
# Libinput configuration for tablets - Auto-generated by termux-wayland-installer

[tablet]
# Pressure curve (0=linear, 1=soft, 2=hard)
PressureCurve=0

# Mapping mode
MapToOutput=

# Rotation (0=none, 1=90, 2=180, 3=270)
Rotation=0

# Button mapping
ButtonMapping=default

[touchpad]
# Touchpad settings (also affects tablet touch strips)
NaturalScrolling=true
TapToClick=true
TapAndDrag=true
TwoFingerTap=right
ThreeFingerTap=middle
ScrollTwoFingers=true
AccelProfile=adaptive
Speed=0.0

[mouse]
AccelProfile=flat
Speed=0.0

[trackpoint]
AccelProfile=flat
Speed=0.0
LIBINPUT_EOF

    log_info "Libinput config created"
}

configure_hyprland_tablet() {
    log_info "Configuring Hyprland tablet support..."

    execute mkdir -p "${HOME}/.config/hypr"

    # Add tablet config to hyprland.conf (append if exists)
    if [[ -f "${HOME}/.config/hypr/hyprland.conf" ]]; then
        if ! grep -q "tablet {" "${HOME}/.config/hypr/hyprland.conf" 2>/dev/null; then
            execute cat >> "${HOME}/.config/hypr/hyprland.conf" << 'HYPR_TABLET_EOF'

# Tablet/Stylus Configuration
tablet {
    # Pressure sensitivity
    pressure_sensitivity = 1.0

    # Button mapping
    button_mapping = default

    # Map to specific output (empty = auto)
    map_to_output =

    # Rotation (0=none, 1=90, 2=180, 3=270)
    rotation = 0

    # Custom tool mappings
    # tool {
    #     name = "Wacom Intuos Pro"
    #     button {
    #         1 = "BTN_LEFT"
    #         2 = "BTN_RIGHT"
    #     }
    # }
}

# Input method tablet integration (fcitx5)
# See fcitx5 config for virtual keyboard on tablet
HYPR_TABLET_EOF
        fi
    fi

    log_info "Hyprland tablet config added"
}

configure_kde_tablet() {
    log_info "Configuring KDE tablet support..."

    execute mkdir -p "${HOME}/.config"

    # KDE tablet config (kcminputrc) - already partially exists in configure_kde()
    # But ensure it's complete for tablet support
    execute cat > "${HOME}/.config/kcminputrc" << 'KDE_TABLET_EOF'
[General]
InputMethod=fcitx5

[GTK]
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

[Tablet]
# Pressure sensitivity (0.0 - 1.0)
PressureSensitivity=1.0

# Pressure curve (0=linear, 1=soft, 2=hard)
PressureCurve=0

# Mode (Absolute/Relative)
Mode=Absolute

# Cursor position mapping
CursorPosition=Screen

# Rotation (0=none, 90, 180, 270)
Rotate=0

# Calibration
Calibrate=false

[Touchpad]
NaturalScrolling=true
TapToClick=true
TapAndDrag=true
TwoFingerTap=RightClick
ThreeFingerTap=MiddleClick
ScrollTwoFingers=true
InvertScrollHoriz=false
InvertScrollVert=false
AccelProfile=adaptive
Speed=0.3

[Mouse]
AccelProfile=flat
Sensitivity=0.0
KDE_TABLET_EOF

    log_info "KDE tablet config (kcminputrc) updated"
}

configure_fcitx5_tablet() {
    log_info "Configuring fcitx5 for tablet virtual keyboard..."

    execute mkdir -p "${HOME}/.config/fcitx5/profile"

    # Add tablet-specific fcitx5 config
    local profile_file="${HOME}/.config/fcitx5/profile/default"
    
    if [[ -f "${profile_file}" ]]; then
        # Check if tablet section exists
        if ! grep -q "TabletMode" "${profile_file}" 2>/dev/null; then
            cat >> "${profile_file}" << 'FCITX_TABLET_EOF'

# Tablet Mode Configuration
[TabletMode]
# Enable virtual keyboard in tablet mode
EnableVirtualKeyboard=true

# Show virtual keyboard when tablet tool touches surface
ShowOnTabletTool=true

# Keyboard layout for tablet
TabletLayout=us

# Auto-hide timeout (ms)
AutoHideTimeout=3000

# Position (bottom, top, center)
Position=bottom
FCITX_TABLET_EOF
        fi
    else
        # Create profile with tablet config (input method hasn't run yet)
        cat > "${profile_file}" << 'FCITX_TABLET_EOF'
[Groups/0]
Name=Default
Default Layout=us
DefaultIM=keyboard-us

[Groups/0/Items/0]
Name=keyboard-us
Layout=us

[Groups/1]
Name=Chinese
Default Layout=us
DefaultIM=pinyin

[Groups/1/Items/0]
Name=keyboard-us
Layout=us

[Groups/1/Items/1]
Name=pinyin
Layout=us

[Groups/2]
Name=Japanese
Default Layout=us
DefaultIM=anthy

[Groups/2/Items/0]
Name=keyboard-us
Layout=us

[Groups/2/Items/1]
Name=anthy
Layout=us

[Groups/3]
Name=Korean
Default Layout=us
DefaultIM=hangul

[Groups/3/Items/0]
Name=keyboard-us
Layout=us

[Groups/3/Items/1]
Name=hangul
Layout=us

[Hotkeys]
TriggerKey=CTRL_SPACE
SwitchKey=ALT_SPACE

# Tablet Mode Configuration
[TabletMode]
# Enable virtual keyboard in tablet mode
EnableVirtualKeyboard=true

# Show virtual keyboard when tablet tool touches surface
ShowOnTabletTool=true

# Keyboard layout for tablet
TabletLayout=us

# Auto-hide timeout (ms)
AutoHideTimeout=3000

# Position (bottom, top, center)
Position=bottom
FCITX_TABLET_EOF
    fi

    # Create fcitx5 tablet trigger script
    execute mkdir -p "${HOME}/.local/bin"
    cat > "${HOME}/.local/bin/fcitx5-tablet-mode" << 'FCITX_TABLET_SCRIPT_EOF'
#!/data/data/com.termux/files/usr/bin/bash
# fcitx5 Tablet Mode Toggle
# Auto-generated by termux-wayland-installer

CONFIG_FILE="${HOME}/.config/fcitx5/profile/default"

toggle_tablet_mode() {
    if grep -q "EnableVirtualKeyboard=true" "${CONFIG_FILE}" 2>/dev/null; then
        # Disable
        sed -i 's/EnableVirtualKeyboard=true/EnableVirtualKeyboard=false/' "${CONFIG_FILE}"
        sed -i 's/ShowOnTabletTool=true/ShowOnTabletTool=false/' "${CONFIG_FILE}"
        echo "Tablet mode: DISABLED"
    else
        # Enable
        sed -i 's/EnableVirtualKeyboard=false/EnableVirtualKeyboard=true/' "${CONFIG_FILE}"
        sed -i 's/ShowOnTabletTool=false/ShowOnTabletTool=true/' "${CONFIG_FILE}"
        echo "Tablet mode: ENABLED"
    fi

    # Restart fcitx5 if running
    if pgrep -x "fcitx5" >/dev/null 2>&1; then
        fcitx5 -r &
    fi
}

case "${1:-toggle}" in
    on|enable)
        sed -i 's/EnableVirtualKeyboard=false/EnableVirtualKeyboard=true/' "${CONFIG_FILE}"
        sed -i 's/ShowOnTabletTool=false/ShowOnTabletTool=true/' "${CONFIG_FILE}"
        pgrep -x "fcitx5" >/dev/null 2>&1 && fcitx5 -r &
        echo "Tablet mode: ENABLED"
        ;;
    off|disable)
        sed -i 's/EnableVirtualKeyboard=true/EnableVirtualKeyboard=false/' "${CONFIG_FILE}"
        sed -i 's/ShowOnTabletTool=true/ShowOnTabletTool=false/' "${CONFIG_FILE}"
        pgrep -x "fcitx5" >/dev/null 2>&1 && fcitx5 -r &
        echo "Tablet mode: DISABLED"
        ;;
    toggle|*)
        toggle_tablet_mode
        ;;
esac
FCITX_TABLET_SCRIPT_EOF
    execute chmod +x "${HOME}/.local/bin/fcitx5-tablet-mode"

    log_info "fcitx5 tablet mode script created at ~/.local/bin/fcitx5-tablet-mode"
}

# Test tablet detection
test_tablet_detection() {
    log_info "Testing tablet device detection..."

    local found=false

    # Check for Wacom
    if ls /dev/input/by-id/ 2>/dev/null | grep -qi wacom; then
        log_info "  Wacom device detected"
        found=true
    fi

    # Check for S-Pen (Samsung)
    if ls /dev/input/by-id/ 2>/dev/null | grep -qi "s-pen\|spen\|sec_touch"; then
        log_info "  Samsung S-Pen detected"
        found=true
    fi

    # Check for generic tablets
    if ls /dev/input/ 2>/dev/null | grep -q "event"; then
        for event in /dev/input/event*; do
            name=$(udevadm info --query=property --name="${event}" 2>/dev/null | grep "ID_INPUT_TABLET=1" || true)
            if [[ -n "${name}" ]]; then
                log_info "  Tablet device: ${event}"
                found=true
            fi
        done
    fi

    if [[ "${found}" != "true" ]]; then
        log_warn "  No tablet devices detected (this is normal if not connected)"
    fi
}

export -f step_tablet_support configure_tablet_udev_rules configure_libinput_tablet
export -f configure_hyprland_tablet configure_kde_tablet configure_fcitx5_tablet
export -f test_tablet_detection